In [1]:
import numpy as np
import pandas as pd

import os

In [5]:
dataset = pd.read_csv("data_02.csv")
print('Load the datasets...')

# Print the shape of the dataset
print ('dataset: %s'%(str(dataset.shape)))
dataset

Load the datasets...
dataset: (15, 4)


Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0       Yes
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0        No
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       Yes
14  Sri lanka  33.0  22000.0        No

In [7]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, 3].values

In [12]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

# Fit imputer for columns 1 and 2 of X matrix.
imputer = imputer.fit(X[:, 1:3])

#Replace missing data with mean of column
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['India', 34.0, 92000.0],
       ['Sri lanka', 22.0, 25000.0],
       ['China', 31.0, 74000.0],
       ['Sri lanka', 29.0, 54857.142857142855],
       ['China', 55.0, 98000.0],
       ['India', 24.0, 30000.0],
       ['Sri lanka', 28.0, 40000.0],
       ['India', 33.714285714285715, 60000.0],
       ['China', 51.0, 89000.0],
       ['India', 44.0, 78000.0],
       ['Sri lanka', 21.0, 20000.0],
       ['China', 25.0, 30000.0],
       ['India', 33.0, 45000.0],
       ['India', 42.0, 65000.0],
       ['Sri lanka', 33.0, 22000.0]], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X[:, 0]

array([1, 2, 0, 2, 0, 1, 2, 1, 0, 1, 2, 0, 1, 1, 2], dtype=object)

In [15]:
# The above method will create problems for us as the model could create a correlation between rows
# Hence we use OneHotEncoder
from sklearn.compose import ColumnTransformer
column_transformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = column_transformer.fit_transform(X)
X

array([[0.0, 1.0, 0.0, 34.0, 92000.0],
       [0.0, 0.0, 1.0, 22.0, 25000.0],
       [1.0, 0.0, 0.0, 31.0, 74000.0],
       [0.0, 0.0, 1.0, 29.0, 54857.142857142855],
       [1.0, 0.0, 0.0, 55.0, 98000.0],
       [0.0, 1.0, 0.0, 24.0, 30000.0],
       [0.0, 0.0, 1.0, 28.0, 40000.0],
       [0.0, 1.0, 0.0, 33.714285714285715, 60000.0],
       [1.0, 0.0, 0.0, 51.0, 89000.0],
       [0.0, 1.0, 0.0, 44.0, 78000.0],
       [0.0, 0.0, 1.0, 21.0, 20000.0],
       [1.0, 0.0, 0.0, 25.0, 30000.0],
       [0.0, 1.0, 0.0, 33.0, 45000.0],
       [0.0, 1.0, 0.0, 42.0, 65000.0],
       [0.0, 0.0, 1.0, 33.0, 22000.0]], dtype=object)

In [16]:
# Encoding the categorical data for Y matrix
labelencoder_Y = LabelEncoder()
Y = labelencoder_X.fit_transform(Y)
Y

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0])

In [18]:
from sklearn.model_selection import train_test_split

# The test size is taken as 20% of the total dataset i.e., out of 15 only 3 rows are taken as test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [19]:
# Feature scaling
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

# We need to fit and transform the training set
X_train = sc_X.fit_transform(X_train)

# We need to fit the test set
X_test = sc_X.transform(X_test)